version: '3.3'

services:
  home_assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - '8123:8123'
    volumes:
      - ./home-assistant/configuration.yaml:/config/configuration.yaml
    environment:
      TZ: 'Asia/Manila'


