default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml

logger:
  default: warning
  logs:
    custom_components.webrtc: debug
